// Command modules for yargs
export { convertCommand } from "./convert.ts"
export { infoCommand } from "./info.ts"
export { trimCommand } from "./trim.ts"
export { compressCommand } from "./compress.ts"
export { extractCommand } from "./extract.ts"
export { mergeCommand } from "./merge.ts"
export { gifCommand } from "./gif.ts"
export { thumbnailCommand } from "./thumbnail.ts"
export { imgConvertCommand } from "./img-convert.ts"
export { imgScaleCommand } from "./img-scale.ts"
export { imgCropCommand } from "./img-crop.ts"
export { imgCompressCommand } from "./img-compress.ts"

// Programmatic functions for TUI usage
export { convert } from "./convert.ts"
export { info } from "./info.ts"
export { trim } from "./trim.ts"
export { compress } from "./compress.ts"
export { extract } from "./extract.ts"
export { merge } from "./merge.ts"
export { gif } from "./gif.ts"
export { thumbnail } from "./thumbnail.ts"
export { imgConvert } from "./img-convert.ts"
export { imgScale } from "./img-scale.ts"
export { imgCrop } from "./img-crop.ts"
export { imgCompress } from "./img-compress.ts"

// Re-export types
export type { TrimOptions } from "./trim.ts"
export type { CompressOptions } from "./compress.ts"
export type { ExtractOptions } from "./extract.ts"
export type { MergeOptions } from "./merge.ts"
export type { GifOptions } from "./gif.ts"
export type { ThumbnailOptions } from "./thumbnail.ts"
export type { ImgConvertOptions } from "./img-convert.ts"
export type { ImgScaleOptions } from "./img-scale.ts"
export type { ImgCropOptions } from "./img-crop.ts"
export type { ImgCompressOptions } from "./img-compress.ts"
